export const fieldInstructions: Record<string, string> = {
  project_name: 'Nombre real del proyecto detectado en package.json, documentacion, configuracion o carpeta raiz.',
  screenshot_path: 'Ruta de imagen o GIF representativo del proyecto. Dejalo vacio si no hay evidencia clara.',
  'summary.what_is': 'Resumen claro de que hace el proyecto y que problema resuelve.',
  'summary.project_type': 'Tipo de proyecto: extension VS Code, API, chatbot, agente, backend, frontend, libreria, CLI, servicio interno u otro.',
  'summary.purpose': 'Objetivo principal del proyecto y valor que aporta al usuario o al equipo.',
  'summary.target_users': 'Perfiles que usaran, mantendran o se beneficiaran de la solucion.',
  'summary.status': 'Estado del proyecto si hay evidencia: prototipo, desarrollo, produccion, mantenimiento, archivado u otro.',
  'summary.success_criteria': 'Como se evalua si el proyecto cumple su objetivo o cuando se considera exitoso.',
  'scope.includes': 'Capacidades, modulos, responsabilidades o funcionalidades cubiertas por el proyecto.',
  'scope.excludes': 'Exclusiones explicitas, responsabilidades fuera de alcance o limites funcionales.',
  'scope.known_limitations': 'Restricciones tecnicas, funcionales, dependencias o limitaciones conocidas que afecten al uso.',
  'usage.channels': 'Canales de uso detectados: web, Teams, API, VS Code, backend interno, CLI u otros.',
  'usage.languages': 'Idiomas soportados. Incluye solo los que aparezcan en codigo, configuracion o documentacion.',
  'usage.contexts': 'Escenarios reales en los que se espera usar la solucion.',
  'ux.start_flow': 'Como empieza la interaccion o ejecucion desde la perspectiva del usuario.',
  'ux.expected_questions': 'Ejemplos de preguntas, tareas, intents o solicitudes que la solucion deberia atender.',
  'ux.attachments_support': 'Si acepta archivos, imagenes u otros adjuntos, y como los usa.',
  'ux.fallback_error_handling': 'Como responde ante errores, baja confianza, excepciones o casos no cubiertos.',
  'ux.human_handoff': 'Si existe escalado a una persona, equipo, canal de soporte o proceso manual.',
  'ux.history_session_memory': 'Si mantiene contexto, memoria, historial de sesion o conversaciones previas.',
  'architecture.logical_flow': `Genera un diagrama visual atractivo y compacto en formato Mermaid que muestre el flujo lógico entre usuario, interfaz, componentes internos y servicios externos. Salida requerida:\n1. Un bloque fenced de Mermaid (indica: tres backticks, la palabra "mermaid", luego el diagrama y cierra con tres backticks) con un diagrama de flujo o gráfico de arquitectura (usa subgraph/flowchart, flechas claras, nombres legibles y anotaciones breves).\n2. Una línea breve (1-2 frases) como leyenda/epígrafe que explique el objetivo del diagrama.\n3. Si no es posible generar Mermaid, producir una alternativa textual compacta (máx. 3 líneas).\n- Prioriza claridad visual: agrupa componentes (UI, extension, scanner/ranker, prompt builder, modelo/Responses API, renderer/preview, storage) y marca la dirección principal de datos (entradas → procesamiento → modelo → renderizado → usuario).\n- No añadas largos párrafos ni listas; sólo el bloque Mermaid seguido de la leyenda.\n\nEjemplo mínimo de salida esperada:\n\n(flowchart LR)\n  subgraph Usuario\n    U[Usuario]\n  end\n  subgraph Cliente\n    UI[UI / VSCode]\n    Edit[Editor / Preview]\n  end\n  subgraph Backend\n    Scan[Scanner]\n    Rank[Ranker]\n    Prompt[Prompt Builder]\n    Azure[Azure OpenAI Responses]\n    Renderer[Template Renderer]\n    Store[README.generated.md]\n  end\n  U --> UI --> Scan --> Rank --> Prompt --> Azure --> Renderer --> Edit\n  Renderer --> Store\n  classDef cloud fill:#f0f8ff,stroke:#0366d6;\n  class Azure cloud\n`,
  'architecture.components': 'Componentes clave del sistema y responsabilidad principal de cada uno.',
  'architecture.external_dependencies': 'Servicios, APIs, bases de datos, modelos, colas, buscadores o integraciones externas.',
  'knowledge_prompts.sources': 'Fuentes de conocimiento: documentos, indices, APIs, bases de datos, ficheros o repositorios.',
  'knowledge_prompts.rag_summary': 'Uso de RAG, embeddings, busqueda semantica o recuperacion documental, si aplica.',
  'knowledge_prompts.prompt_guardrails_location': 'Donde estan los prompts, instrucciones de agente, politicas o guardrails.',
  'knowledge_prompts.forbidden_content_handling': 'Como se gestionan restricciones, moderacion o respuestas no permitidas.',
  'security_privacy.processed_data': 'Tipos de datos procesados, especialmente datos personales, sensibles o corporativos.',
  'security_privacy.retention_storage': 'Si los datos se almacenan, donde se almacenan y durante cuanto tiempo, solo con evidencia.',
  'security_privacy.access_auth': 'Autenticacion, autorizacion, roles o controles de acceso detectados.',
  'security_privacy.anonymization_secrets': 'Masking, anonimizacion, gestion de secretos o proteccion de credenciales.',
  'security_privacy.compliance_notes': 'Notas de cumplimiento, privacidad o normativa mencionadas en el proyecto.',
  'local_development.requirements': 'Runtimes, versiones, dependencias, herramientas y servicios necesarios para desarrollo local.',
  'local_development.env_variables': 'Variables de entorno detectadas y finalidad de cada una si es evidente.',
  'local_development.env_variables.name': 'Nombre exacto de la variable de entorno.',
  'local_development.env_variables.description': 'Finalidad de la variable de entorno, solo si puede inferirse con evidencia.',
  'local_development.resources': 'Datos, ficheros, indices, recursos cloud o dependencias externas necesarias.',
  'local_development.install_run_commands': 'Comandos de instalacion, arranque y uso local encontrados en scripts o documentacion.',
  'local_development.validation_checks': 'Comandos o pasos breves para comprobar que el proyecto funciona.',
  'local_development.testing_strategy': 'Estrategia, framework o comandos de pruebas documentados.',
  'deployment.environments': 'Entornos detectados: local, desarrollo, preproduccion, produccion, cloud u otros.',
  'deployment.process': 'Como se despliega segun pipelines, Docker, IaC, scripts o documentacion.',
  'deployment.environment_differences': 'Diferencias de configuracion, recursos o comportamiento entre entornos.',
  'operations.logs': 'Donde consultar logs o como se generan, si hay evidencia.',
  'operations.traces': 'Donde consultar trazas o como se instrumentan, si hay evidencia.',
  'operations.metrics': 'Metricas disponibles o herramientas de monitorizacion detectadas.',
  'operations.alerts_runbooks': 'Alertas, runbooks o procedimientos operativos detectados.',
  'operations.incident_process': 'Como se gestionan incidencias o soporte operativo si esta documentado.',
  'documentation_links.coordination_tools': 'Herramientas de gestion, tickets, coordinacion o seguimiento mencionadas.',
  'documentation_links.repos_pipelines': 'Repositorios, pipelines, workflows o recursos de CI/CD mencionados.',
  'documentation_links.environments_resources': 'Referencias a entornos, recursos cloud, dashboards o servicios.',
  'documentation_links.manuals_docs': 'Manuales, documentacion tecnica, guias o archivos relevantes del repositorio.',
  roadmap: 'Mejoras futuras, TODOs o elementos de roadmap mencionados explicitamente.',
  'contacts.product_owner': 'Product owner. Rellena solo si aparece explicitamente.',
  'contacts.technical_owner': 'Responsable tecnico. Rellena solo si hay evidencia clara.',
  'contacts.responsible_team': 'Equipo propietario o responsable si aparece en documentacion o metadatos.',
  'contacts.support_operations': 'Canal o equipo de soporte/operacion solo si esta documentado.',
  related_projects: 'Proyectos relacionados mencionados explicitamente en el repositorio.'
};

export function buildFieldInstructionText(): string {
  return Object.entries(fieldInstructions)
    .map(([path, description]) => `- ${path}: ${description}`)
    .join('\n');
}

export function getFieldInstruction(path: string): string | undefined {
  return fieldInstructions[path];
}
